# Generated by Django 5.0.4 on 2024-05-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_new_combrate', '0002_supporter_my_new_combrate_supporters'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
